apiVersion: v1
kind: ReplicationController
metadata:
  name: web-app-dev
spec:
  replicas: 3
  selector:
    app: web-app-dev
  template:
    metadata:
      name: web-app-dev
      labels:
        app: web-app-dev
    spec:
      containers:
      - name: web-app-dev
        image: ovaleanu/webapp
        ports:
        - containerPort: 80
